### ISSUE TITLE
Encountered in the use of a mailbox problem

### ISSUE THREAD

**Issue by ss958** [azerothcore/mod-premium#8] opened 2018-02-15 03:55 UTC
Open the mailbox can not be used when using and sending mail, and the system's own mailbox will also have this problem, you must go offline and can be resolved.

**Comment by Knindzagxg** [comment] 2018-06-22 13:59
I can confirm this.
Mail does not work when used trough Premium.

**Comment by BarbzYHOOL** [comment] 2018-06-22 22:07
Need @talamortis

**Comment by poszer** [comment] 2018-11-07 01:08
Confirmed. Mailbox doesn't work
[Video](https://youtu.be/WY6Vt_G_5OE)

**Comment by talamortis** [comment] 2018-11-07 11:59
This issue is due to a core check in the MailHandler.cpp  if you want to fix it you will need to do some core edits chnage the following code from
`bool WorldSession::CanOpenMailBox(uint64 guid)
{
    if (guid == _player->GetGUID())
    {
        sLog->outError("%s attempt open mailbox in cheating way.", _player->GetName().c_str());
        return false;
    }
    else if (IS_GAMEOBJECT_GUID(guid))
    {
        if (!_player->GetGameObjectIfCanInteractWith(guid, GAMEOBJECT_TYPE_MAILBOX))
            return false;
    }
    else if (IS_CRE_OR_VEH_OR_PET_GUID(guid))
    {
        if (!_player->GetNPCIfCanInteractWith(guid, UNIT_NPC_FLAG_MAILBOX))
            return false;
    }
    else
        return false;


    return true;
}`

change to

`bool WorldSession::CanOpenMailBox(uint64 guid)
{
if (IS_GAMEOBJECT_GUID(guid))
    {
        if (!_player->GetGameObjectIfCanInteractWith(guid, GAMEOBJECT_TYPE_MAILBOX))
            return false;
    }
    else if (IS_CRE_OR_VEH_OR_PET_GUID(guid))
    {
        if (!_player->GetNPCIfCanInteractWith(guid, UNIT_NPC_FLAG_MAILBOX))
            return false;
    }
    else
        return false;

    return true;
}`

**Comment by poszer** [comment] 2018-11-17 23:16
Thanks @talamortis

**Comment by talamortis** [comment] 2018-11-18 07:14
I will upload a patch to fix this issue. 
Thanks

**Comment by masterking32** [comment] 2018-11-19 16:05
`bool WorldSession::CanOpenMailBox(uint64 guid)
{
 if (IS_CRE_OR_VEH_OR_PET_GUID(guid))
    {
        if (!_player->GetNPCIfCanInteractWith(guid, UNIT_NPC_FLAG_MAILBOX))
            return false;
    }
    else
        return false;

    return true;
}`

alwasy retrun false, bcz it just check, It's creature or pet ....
If you want load it from item just need to change it to : 
`bool WorldSession::CanOpenMailBox(uint64 guid)
{
    if (guid == _player->GetGUID())
    {
        //sLog->outError("%s attempt open mailbox in cheating way.", _player->GetName().c_str());
        return true;
    }
    else if (IS_ITEM_GUID(guid))
    {
        return true;
    }
    else if (IS_GAMEOBJECT_GUID(guid))
    {
        if (!_player->GetGameObjectIfCanInteractWith(guid, GAMEOBJECT_TYPE_MAILBOX))
            return false;
    }
    else if (IS_CRE_OR_VEH_OR_PET_GUID(guid))
    {
        if (!_player->GetNPCIfCanInteractWith(guid, UNIT_NPC_FLAG_MAILBOX))
            return false;
    }
    else
        return false;

    return true;
}`

**Comment by masterking32** [comment] 2018-11-19 16:13
[Click to see the code](https://paste.masterking32.com/code/30-ac-mailbox-alwasy-return-false-problem)
always return false, bcz it just check, It's creature or pet ....
If you want load it from item or player just need to change it to : 
[Fix Patch](https://paste.masterking32.com/code/31-azerothcore-fix-item-open-mailbox)

**Comment by pangolp** [comment] 2023-08-11 09:45
Is this error still occurring or can we close this topic?

**Comment by pangolp** [comment] 2023-08-11 09:46
Due to the release date, this should be resolved by now. If the problem persists, we reopen the issue or create a new one giving a little more information on the subject.

**Closed by pangolp** 2023-08-11 09:46 UTC
Labels: bug
